version: 2.1

executors:
  default:
    docker:
      - image: ccurtsinger/dodo-test:0.0.2
jobs:
  all:
    executor: default
    steps:
      - checkout
      - run: git submodule update --init
      - run: make
      - run: ./dodo build
      #- run: ./dodo graph -o self-build.dot
      #- store_artifacts:
      #    path: self-build.dot
      #- run: dot -Tpdf self-build.dot > self-build.pdf
      #- store_artifacts:
      #    path: self-build.pdf
      #- run: dot -Tsvg self-build.dot > self-build.svg
      #- store_artifacts:
      #    path: self-build.svg
      - run: make test

workflows:
  version: 2
  build-and-test:
    jobs:
      - all:
        branches:
          ignore:
            - apl-proposal
            - paper
            - presentation
